namespace classabbyamp -> miaowware
miaowware/ctyparser pull request #30
Opened 2020-02-11 04:28 UTC by classabbyamp

check if I missed anything

2020-02-11 04:29 UTC, classabbyamp commented
wait we'll have to bump the version right?

2020-02-15 10:50 UTC, 0x5c commented
Not if we use some weird versioning scheme extension supported by PyPI  
https://www.python.org/dev/peps/pep-0440/#post-releases

2020-02-15 15:43 UTC, 0x5c requested changes
Missing:
- version bump: `2.0.0.post1`
- ~~badges in the README~~

2020-02-16 16:11 UTC, 0x5c approved these changes

2020-02-16 16:12 UTC, merged